knpu_oauth2_client:
    clients:
        # configuré dans .env
        google:
            type: google
            client_id: '%env(GOOGLE_CLIENT_ID)%'
            client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
            # un chemin de redirection simple, mais il sera utilisé par le contrôleur
            redirect_route: app_oauth_google_check
            redirect_params: {}

